# Generated by Django 6.0.4 on 2026-04-19 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_invoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
    ]
