# Generated by Django 6.0.4 on 2026-05-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_invoice_options_alter_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user_status_read',
            field=models.BooleanField(default=True),
        ),
    ]
