# Generated by Django 5.0.14 on 2026-05-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_user_status_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='admin_notif_read',
            field=models.BooleanField(default=True),
        ),
    ]
