# Generated by Django 6.0.7 on 2026-08-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_add_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
