# Generated by Django 6.0.7 on 2026-08-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_add_soft_delete_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='admin_reply',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='admin_reply_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
