# Generated by Django 6.0.4 on 2026-04-19 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'Contact message', 'verbose_name_plural': 'Contact messages'},
        ),
    ]
