# Generated by Django 6.0.4 on 2026-05-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contactmessage_admin_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='user_response_read',
            field=models.BooleanField(default=True),
        ),
    ]
