# Generated by Django 6.0.4 on 2026-08-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_add_cancelled_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
