# Generated by Django 6.0.4 on 2026-05-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountstatus',
            name='admin_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='accountstatus',
            name='deletion_reason_type',
            field=models.CharField(choices=[('user_request', 'Demande utilisateur'), ('admin_block', 'Blocage administrateur')], default='user_request', max_length=20),
        ),
    ]
