# Generated by Django 6.0.4 on 2026-08-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_admin_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountstatus',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
