# Generated by Django 6.0.4 on 2026-04-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicleimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclecategory',
            options={'verbose_name': 'Vehicle category', 'verbose_name_plural': 'Vehicle categories'},
        ),
        migrations.AlterModelOptions(
            name='vehicleimage',
            options={'verbose_name': 'Vehicle image', 'verbose_name_plural': 'Vehicle images'},
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], default='available', max_length=20),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['status'], name='vehicles_ve_status_f71f77_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['price'], name='vehicles_ve_price_da359f_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['created_at'], name='vehicles_ve_created_3aff09_idx'),
        ),
    ]
