# Generated by Django 6.0.7 on 2026-08-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_add_favorite_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='carrosserie',
            field=models.CharField(blank=True, choices=[('tres_bon', 'Tres bon etat'), ('bon', 'Bon etat'), ('accidente', 'Legerement accidente')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='condition_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='moteur',
            field=models.CharField(blank=True, choices=[('tres_bon', 'Tres bon'), ('bon', 'Bon'), ('reparation', 'Reparation a prevoir')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Reserve'), ('sold', 'Vendu')], default='available', max_length=20),
        ),
    ]
