# Generated by Django 6.0.7 on 2026-08-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_add_carrosserie_moteur_condition_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='description_nl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='carrosserie',
            field=models.CharField(blank=True, choices=[('tres_bon', 'Tres bon'), ('bon', 'Bon'), ('accidente', 'Legerement accidente')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='moteur',
            field=models.CharField(blank=True, choices=[('tres_bon', 'Tres bon'), ('bon', 'Bon'), ('reparation', 'Roule, reparation mineure a prevoir')], default='', max_length=20),
        ),
    ]
